# Generated by Django 5.0.1 on 2024-02-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='forget_password_token',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
