# Generated by Django 5.0.1 on 2024-02-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureapp', '0002_alter_profile_forget_password_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pincode',
            field=models.CharField(default='a', max_length=150, null=True),
        ),
    ]
