# Generated by Django 5.0.1 on 2024-02-09 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureapp', '0004_alter_profile_forget_password_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
