# Generated by Django 5.0.1 on 2024-02-09 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureapp', '0006_orderitem_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_image',
            new_name='product_image_url',
        ),
    ]
