# Generated by Django 5.0 on 2024-02-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("furnitureapp", "0007_rename_product_image_orderitem_product_image_url"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Slider",
        ),
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(default="Akshith (Default)", max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_img",
            field=models.ImageField(default="/Akki Image.jpg", upload_to="profile/"),
        ),
    ]
